### ISSUE TITLE
service-not-available

### ISSUE THREAD

**Issue by arverne63** [skedgo/leaflet.tripgo.routing#1]
Bonjour,
Je souhaiterais utiliser Leaflet TripGo routing avec une map centrée en france sur Paris.
Les markers ne s'affichent pas et j'ai  le message d’erreur suivant "**service-not-available, The routing service is currently not available,
 please check your API key or try again later**"
En utilisant les coordonnées d'origine ("lat": 51.511011, "lng": -0.125448) tout fonctionne.
Si vous avez une solution, je vous remercie par avance.
J.Marc.
Ci joint le fichier exemple-2.txt
[exemple-2.txt](https://github.com/skedgo/leaflet.tripgo.routing/files/2620807/exemple-2.txt)
, je n'est pas modifié les fichiers js et css.

**Comment by gimenna** [comment]
Hi, 
Sorry but don't speak french, so I'll answer in english...
I've tested and it seems to be working in Paris. I can only reproduce the error when I load the .html page directly from the file instead doing it through a local server.

Could you give me more details about how you are testing it?

Thanks,
Gimena

**Comment by arverne63** [comment]
Bonsoir,
J'ai refais un test à Paris, il fonctionne maintenant mais pas dans le reste de la france.
Je test sur ce site http://testrandos.free.fr/leaflet.tripgo.routing-master/exemple-2.html
Merci
Jean Marc

**Comment by MarianoTucat** [comment]
FTR, we do not cover the entire France yet. You can see our current coverage [here](https://tripgo.skedgo.com/world#tripgo:show).
